import Head from "next/head";
import { Inter } from "@next/font/google";

import HomeAppBar from "../components/organisms/HomeAppBar";
import FilterForm from "../components/organisms/FilterForm";
import Hero from "../components/sections/Hero";
import PlacesGrid from "../components/sections/PlacesGrid";

import { useSelector } from "react-redux";

import AddPlaceForm from "../components/organisms/AddPlaceForm";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const PlacesStore = useSelector((state) => state.places);
  const { showAddModel } = PlacesStore;
  return (
    <>
      <Head>
        <title>Jo Chalets</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main className=" h-auto bg-blue-200">
        <HomeAppBar />

        <Hero />
        <PlacesGrid />
        {showAddModel && (
          <div className="h-full w-full bg-primary bg-opacity-25 backdrop-blur-lg absolute top-0 left-0 z-20">
            <AddPlaceForm />
          </div>
        )}
      </main>
    </>
  );
}
